apiVersion: v1
kind: Service
metadata:
  labels:
    service: connection-services
  name: connection-services
spec:
  ports:
  - name: "5002"
    port: 5002
    targetPort: 5002
    nodePort: 30011
  selector:
    service: connection-services
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: connection-services
  name: connection-services
spec:
  replicas: 1
  selector:
    matchLabels:
      service: connection-services
  template:
    metadata:
      labels:
        service: connection-services
    spec:
      containers:
      - image: chinhnv8/udaconnect:connection_services.v1
        name: connection-services
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always