apiVersion: v1
kind: Service
metadata:
  labels:
    service: location-services
  name: location-svc-api
spec:
  ports:
  - name: "5001"
    port: 5001
    targetPort: 5001
    nodePort: 30032
  selector:
    service: location-services
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: location-services
  name: location-services-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: location-services
  template:
    metadata:
      labels:
        service: location-services
    spec:
      containers:
      - image: chinhnv8/udaconnect:location_services.v1
        name: location-container-services
        imagePullPolicy: Always
        env:
        - name: KAFKA_API
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_API
        - name: KAFKA_TOPICS
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_TOPICS        
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always