apiVersion: v1
kind: Service
metadata:
  labels:
    service: person-services
  name: person-svc-api
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30001
  selector:
    service: person-services
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: person-services
  name: person-deployment-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: person-services
  template:
    metadata:
      labels:
        service: person-services
    spec:
      containers:
      - image: chinhnv8/udaconnect:person_services.v1
        name: person-container-api
        imagePullPolicy: Always
        env:
        - name: KAFKA_API
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_API
        - name: KAFKA_TOPICS
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_TOPICS        
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always